export const arrayItems = [
  {
    name: "Q&A",
    id: "q&a",
    description: "Answer questions based on existing knowledge.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\n"]
    },
  },
  {
    name: "Grammar Correction",
    id: "grammarcorrection",
    description: "Corrects sentences into a standard form of English.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Summarize for a 2nd grader",
    id: "summary",
    description: "Translates difficult text into simpler concepts.",
    option: {
      model: "text-davinci-003",
      temperature: 0.7,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Natural language to GamaAI API",
    id: "language",
    description: "Create code to call to the GamaAI API using a natural language instruction.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\"\"\""],
    },
  },
  {
    name: "Text to command",
    id: "text",
    description: "Translate text into programmatic commands.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.2,
      presence_penalty: 0.0,
      stop: ["\n"],
    },
  },
  {
    name: "SQL translate",
    id: "sqltranslate",
    description: "Translate natural language to SQL queries.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 150,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["#", ";"],
    },
  },
  {
    name: "Parse unstructed data",
    id: "error",
    description: "Creates tables from long form text.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Classification",
    id: "classify",
    description: "Classify items into categories by eg.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Python to natural language",
    id: "convertlanguage",
    description: "Explain a piece of Python code in human understandable language.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Movie to Emoji",
    id: "movietoemoji",
    description: "Convert movie titles into emoji.",
    option: {
      model: "text-davinci-003",
      temperature: 0.8,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\n"],
    },
  },
  {
    name: "Calculate Time Complexity",
    id: "time",
    description: "Find the time complexity of a function.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\n"],
    },
  },
  {
    name: "Translate Programming language",
    id: "programminglanguagetranslator",
    description: "Translate from one programming language to another one.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 54,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["###"],
    },
  },
  {
    name: "Explain Code",
    id: "codeexplanation",
    description: "Explain a complicated piece of code.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\"\"\""],
    },
  },
  {
    name: "Python bug fixer",
    id: "fixesbugs",
    description: "Find and fix bugs in source code.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 182,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["###"],
    },
  },
  {
    name: "SpreadSheet creator",
    id: "creator",
    description: "Create spreadsheets of various kinds of data. It's a long prompt but very versatile. Out.....",
    option: {
      model: "text-davinci-003",
      temperature: 0.5,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript helper chatbox",
    id: "javascripthelperchatbox",
    description: "Message style bot that answers JavaScript questions.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
      stop: ["You:"],
    },
  },
  {
    name: "ML/AI language model tutorial",
    id: "modellanguagetutorial",
    description: "Bot that answers questions about language models.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
      stop: ["You:"],
    },
  },
  {
    name: "SQL request",
    id: "sqlrequest",
    description: "Create simple SQL queries.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript to Python",
    id: "javatopython",
    description: "Converts simple JavaScript expressions into Python.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Friend chat",
    id: "friendchat",
    description: "Emulate a text massage conversation.",
    option: {
      model: "text-davinci-003",
      temperature: 0.5,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
      stop: ["You:"],
    },
  },
  {
    name: "Mood to color",
    id: "mood to color",
    description: "Turn a text description into a color.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: [";"],
    },
  },
  {
    name: "Write a Python docstring",
    id: "pythondocstring",
    description: "An example of how to create a docstring for a given Python function. We specify the Python.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 150,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["#", "\"\"\""],
    },
  },
  {
    name: "Analog maker",
    id: "analogmaker",
    description: "Create analogies. Modified from a community prompt to require fewer examples.",
    option: {
      model: "text-davinci-003",
      temperature: 0.5,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript one line funtion",
    id: "converts javascript into a line",
    description: "Turn a JavaScript function into a one line.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: [";"],
    },
  },
  {
    name: "Mini horror story creator",
    id: "short story",
    description: "Creates two to three sentence short horror stories from a topic input.",
    option: {
      model: "text-davinci-003",
      temperature: 0.8,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Third person converter",
    id: "talk to third person",
    description: "Converts first person POV to the third person. This is modified from a community pro....",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Notes to summary",
    id: "notes to summary",
    description: "Turn meeting notes into a summary.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "VR fitness idea generator",
    id: "generates vr fitness idea",
    description: "Create ideas for fitness and virtual reality games.",
    option: {
      model: "text-davinci-003",
      temperature: 0.6,
      max_tokens: 150,
      top_p: 1.0,
      frequency_penalty: 1,
      presence_penalty: 1,
    },
  },
  {
    name: "Essay outline",
    id: "gives a essay",
    description: "Generates an outline for a research on any topic.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 150,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Chat",
    id: "chat",
    description: "Open ended conversation with an AI assistant.",
    option: {
      model: "text-davinci-003",
      temperature: 0.9,
      max_tokens: 150,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.6,
      stop: [" Human:", " AI:"],
    },
  },
  {
    name: "Create study Notes",
    id: "create study notes",
    description: "Provide sufficient info related to any topic.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 150,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "English to other languages",
    id: "convert language",
    description: "Translate English text to French, Spanish and Japanese.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
]